### ISSUE TITLE
[Releng] Add Oomph support

### ISSUE THREAD

**Issue by slizaa** [slizaa/slizaa#19]
- https://wiki.eclipse.org/Eclipse_Oomph_Authoring

**Comment by wuetherich** [comment]
https://projects.eclipse.org/projects/tools.oomph
http://wiki.eclipse.org/Eclipse_Installer
http://wiki.eclipse.org/Eclipse_Oomph_Authoring

https://timdelbruegger.wordpress.com/2015/08/16/automating-project-specific-eclipse-setups-with-oomph/
https://www.winklerweb.net/index.php/blog/12-eclipse/20-creating-custom-installations-with-oomph

https://github.com/joergreichert/oomph-catalogue#general-hints

http://codeandme.blogspot.de/p/oomph-articles.html
http://www.lorenzobettini.it/2015/10/oomph-setup-for-xtext-projects/

http://eclipsesource.com/blogs/2015/08/17/introducing-the-eclipsesource-oomph-profile/

https://github.com/joergreichert/oomph-catalogue/blob/master/setups/com.github.projects.setup

https://www.youtube.com/watch?v=_QlSosecEUo

https://www.eclipse.org/forums/index.php/t/1077443/
https://www.eclipse.org/forums/index.php/sf/thread/287/1/120/
https://www.eclipse.org/forums/index.php/t/796305/
https://www.eclipse.org/forums/index.php/t/1069326/
http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/Oomph.setup
