### ISSUE TITLE
How to pronounce Slizaa?

### ISSUE THREAD

**Issue by szarnyasg** [slizaa/slizaa#72]
I am going to mention the Slizaa openCypher grammar in my [FOSDEM talk](https://fosdem.org/2017/schedule/event/graph_incremental_queries_open_cypher/) tomorrow. Do you have any preference on how to pronounce it? Is it [slizə], [slizəə], [slaɪzə] or something else?

**Comment by wuetherich** [comment]
Hi, that's cool. You can pronounce it [slaɪzɑ].

2017-02-03 11:16 GMT+01:00 Gabor Szarnyas <notifications@github.com>:

**Comment by szarnyasg** [comment]
Thanks for the quick reply!
